theme: jekyll-theme-minimal
title: Paweł Wołoszyn
description: Fullstack developer, pracujący w technologiach .NET Core i Angular. Chętnie poszerzam swoje kompetencje w różnych technologiach.
logo: assets/logo.jpg
show_downloads: false
locale: pl-PL
github:
  is_user_page: false
