theme: jekyll-theme-minimal
title: Paweł Wołoszyn
description: Fullstack developer z Gliwic, pracujący w technologiach .NET Core i Angular
logo: assets/logo.jpg
show_downloads: false
github:
  is_user_page: false
